services:
  
  postgres:
    image: 'postgres:alpine'
    container_name: 'postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'

  php:
    build: ./
    container_name: 'php'
    volumes:
      - ./app:/var/www/symfony
    environment:
      - 'DATABASE_URL=postgres://postgres:password@postgres:5432/ecommerce'
    ports:
      - '8000:8000'