version: '3.8'

services:
  
  postgres:
    image: 'postgres:alpine'
    container_name: 'postgres'
    volumes:
      - './postgres_data:/var/lib/postgresql'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'

  php:
    build: ./app
    container_name: 'php'
    volumes:
      - './app:/var/www/symfony'
    environment:
      - 'DATABASE_URL=postgres://postgres:password@postgres:5432/ecommerce'
    ports:
      - '8000:8000'