lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 43200

    encoder:
        # token encoder/decoder service - default implementation based on the lcobucci/jwt library
        service:
            lexik_jwt_authentication.encoder.lcobucci

    token_extractors:
        authorization_header:
            enabled: true
            prefix: 'Bearer'
            name: Authorization
        cookie:
            enabled: true
            name: access_token
    
    set_cookies:
        access_token: ~
    remove_token_from_body_when_cookies_used: true